# Generated by Django 3.2.6 on 2021-08-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('subtitile', models.CharField(max_length=250)),
                ('button_Text', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='media/slider/%Y/%m')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
