# Generated by Django 3.2.6 on 2021-08-17 16:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Canon', 'Canon'), ('Nikon', 'Nikon'), ('Sony', 'Sony'), ('Red', 'Red'), ('Fuji', 'Fuji'), ('Panasonic', 'Panasonic'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Code', 'Code'), ('Mobile review', 'Mobile review'), ('Comedy', 'Comedy'), ('Vlogs', 'Vlogs'), ('Gaming', 'Gaming'), ('Cooking', 'Cooking'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Small', 'Small'), ('Large', 'Large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
